# Generated by Django 4.2.23 on 2025-07-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('JEFE_MESA', 'Jefe de Mesa'), ('EJECUTIVO_AYUDA', 'Ejecutivo de Mesa de Ayuda'), ('EJECUTIVO_AREA', 'Ejecutivo de Área Específica')], default='EJECUTIVO_AYUDA', max_length=20),
        ),
    ]
